- name: expense backend setup
  hosts: all
  become: yes
  tasks:
    - name: disable nodejs
      ansible.builtin.shell: dnf module disable nodejs -y
    - name: enable nodejs:18 version
      ansible.builtin.shell: dnf module enable nodejs:18 -y
    - name: installing nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: copying backend service
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service
    - name: adding user
      ansible.builtin.user:
        name: expense
    - name: delete old app directory
      ansible.builtin.file:
        path: /app
        state: absent
    - name: creating directory
      ansible.builtin.file:
        name: /app
        state: directory
    - name: download and extract app content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
    - name: download nodejs dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app
    - name: install mysql client
      ansible.builtin.dnf:
        name: mysql
        state: present
    - name: loading the schema
      ansible.builtin.shell: mysql -h mysq-dev.devops76.online -uroot -p{{MYSQL_ROOT_PASSWORD}} < /app/schema/backend.sql
    - name: start backend service
      ansible.builtiin.systemd:
        name: backend
        state: restarted
        daemon-reload: yes