- name: disabling the nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enabling the nodejs:18 version
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: installing the node js
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: copy backend.service
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: creating the user
  ansible.builtin.user:
    name: expense

- name: import common role app pre-requsities
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir: /app
    component: backend

- name: download dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: installing mysql client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: loading schema
  ansible.builtin.shell: mysql -h mysql-dev.devops76.online -uroot -p{{MYSQL_ROOT_PASSWORD}} < /app/schema/backend.sql

- name: starting backend service
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
    daemon-reload: yes
